name: indentation

on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:

  ################
  # clang-format #
  ################

  clang-format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: clang-format
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: 'source tests'
        clangFormatVersion: 16.0.3
